# Generated by Django 3.0.5 on 2020-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
